version: '3.8'

services:
  db:
    image: postgres:16.3
    container_name: country-authority-etl-postgres
    restart: always
    environment:
      POSTGRES_DB: country-authority
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
