---
{{ if .Values.countryAuthorityEtl.k8s.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  maxReplicas: {{ .Values.countryAuthorityEtl.k8s.hpa.maxReplicas }}
  minReplicas: {{ .Values.countryAuthorityEtl.k8s.replicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: {{ .Values.countryAuthorityEtl.k8s.hpa.targetCPUUtilizationPercentage }}
        type: Utilization
    type: Resource
{{ end }}
