apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  {{- if .Values.countryAuthorityEtl.k8s.ingress.annotations }}
  annotations:
{{ toYaml .Values.countryAuthorityEtl.k8s.ingress.annotations | indent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ tpl .Values.countryAuthorityEtl.host $ }}
    http: &http_rules
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: 80
  {{- range .Values.countryAuthorityEtl.k8s.ingress.hosts }}
  - host: {{ . }}
    http: *http_rules
  {{- end }}
  {{- if .Values.countryAuthorityEtl.k8s.ingress.tls }}
  tls:
{{ toYaml .Values.countryAuthorityEtl.k8s.ingress.tls | indent 2}}
  {{- end }}
