apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
{{ toYaml .Values.countryAuthorityEtl.k8s.service.annotations | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
